idp_app_token: rtTeQADRg5KgDslQR0OAvyPyQbw2GCxW
idp_auth_endpoint: https://idp.ccc.ocre.cea.fr/auth/realms/minio/protocol/openid-connect/token

s3_credential_file: ~/.rift/auth.json
s3_auth_endpoint:  https://annexe-forge.ccc.ocre.cea.fr

annex: https://harbor-forge.ccc.ocre.cea.fr/ocean/annex
annex_is_s3: false
annex_push: https://annexe-forge.ccc.ocre.cea.fr/oceantest/paratools-annex

## scenario 1a
#annex: file:///root/annex
#annex_push: https://s3.amazonaws.com/cache.e4s.io/ocean/annex
#
## scenario 1b
#annex: /root/annex
#annex_push: https://s3.amazonaws.com/cache.e4s.io/ocean/annex
#
## scenario 2a
#annex: https://cache.e4s.io/ocean/annex
#annex_is_s3: no
#annex_push: https://s3.amazonaws.com/cache.e4s.io/ocean/annex
#
## scenario 3a
#annex: https://s3.amazonaws.com/cache.e4s.io/ocean/annex
#annex_is_s3: yes
#annex_push: https://s3.amazonaws.com/cache.e4s.io/ocean/annex
#
## scenario 3b
#annex: https://s3.amazonaws.com/cache.e4s.io/ocean/annex
#annex_is_s3: yes
#
## scenario 4a
#annex: https://s3.amazonaws.com/cache.e4s.io/ocean/annex
#annex_is_s3: yes
#annex_push: file:///root/annex
#
## scenario 4b
#annex: https://s3.amazonaws.com/cache.e4s.io/ocean/annex
#annex_is_s3: yes
#annex_push: /root/annex

# annex_restore_cache: ~/.rift/annex_restore_cache

# Project version
version: master

# VM options
vm_image: /root/vm/centos-9.4-v4.4-x86_64.qcow
vm_image_copy: 1
shared_fs_type: virtiofs

# Qemu path
#qemu: /usr/libexec/qemu-kvm

# External repositories
repos:
    os:
        url:      https://repo.almalinux.org/vault/9.4/BaseOS/x86_64/os
        priority: 90
    updates:
        url:      https://repo.almalinux.org/vault/9.4/AppStream/x86_64/os
        priority: 90
    crb:
        url:      https://repo.almalinux.org/vault/9.4/CRB/x86_64/os/
        priority: 90
    extras:
        url:      https://repo.almalinux.org/vault/9.4/extras/x86_64/os
        priority: 90
    ha:
        url:      https://repo.almalinux.org/vault/9.4/HighAvailability/x86_64/os
        priority: 90
    debuginfo:
        url:      https://repo.almalinux.org/vault/9.4/BaseOS/debug/x86_64
        priority: 90
    epel:
        url:      https://dl.fedoraproject.org/pub/epel/9/Everything/x86_64
        priority: 90
    mofed:
        url:      http://linux.mellanox.com/public/repo/mlnx_ofed/5.8-4.1.5.0/rhel9.3/x86_64
        priority: 90
    influx:
        url:      https://repos.influxdata.com/rhel/9/x86_64/stable/
        priority: 90
    puppet:
        url:      http://yum.puppetlabs.com/puppet/el/9/x86_64
        priority: 90
    mongodb:
        url:      https://repo.mongodb.org/yum/redhat/9/mongodb-org/8.0/x86_64/
        priority: 90
    ocean:
        url: https://ocean.eupex.eu/download/4.4/ocean/x86_64/
        #url:      file:///ccc/home/cont001/ocean/ocean/packages/master/ocean/x86_64
        module_hotfixes: true
